/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'admin-notification': RouteRecordInfo<'admin-notification', '/admin/notification', Record<never, never>, Record<never, never>>,
    'admin-notification-payment-id': RouteRecordInfo<'admin-notification-payment-id', '/admin/notification/payment/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'admin-notification-registration-email': RouteRecordInfo<'admin-notification-registration-email', '/admin/notification/registration/:email', { email: ParamValue<true> }, { email: ParamValue<false> }>,
    'admin-payment-list': RouteRecordInfo<'admin-payment-list', '/admin/payment/list', Record<never, never>, Record<never, never>>,
    'admin-student-add': RouteRecordInfo<'admin-student-add', '/admin/student/add', Record<never, never>, Record<never, never>>,
    'admin-student-details-code': RouteRecordInfo<'admin-student-details-code', '/admin/student/details/:code', { code: ParamValue<true> }, { code: ParamValue<false> }>,
    'admin-student-list': RouteRecordInfo<'admin-student-list', '/admin/student/list', Record<never, never>, Record<never, never>>,
    'admin-user-list-pending': RouteRecordInfo<'admin-user-list-pending', '/admin/user/list-pending', Record<never, never>, Record<never, never>>,
    'change-password': RouteRecordInfo<'change-password', '/change-password', Record<never, never>, Record<never, never>>,
    'force-change-password': RouteRecordInfo<'force-change-password', '/force-change-password', Record<never, never>, Record<never, never>>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'profile': RouteRecordInfo<'profile', '/profile', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'student-id': RouteRecordInfo<'student-id', '/student/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'student-payments-student': RouteRecordInfo<'student-payments-student', '/student/payments-student', Record<never, never>, Record<never, never>>,
  }
}
